# This is a basic workflow to help you get started with Actions

name: Auto-Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Docker login
        uses: azure/docker-login@v1
        with:
          username: p208p2002
          password: ${{ secrets.DOCKER_HUB_PWD }}
      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - name: Build and Push
        run: docker buildx build --platform linux/arm64,linux/amd64 -t=p208p2002/transformer-qg-on-squad:lastest . --push
      
